apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: densityplays
  namespace: densityplays
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd-hostpath
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
